version: 2.1

jobs:
  build_and_create_sbom:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Install Syft"
          command: |
            mkdir -p "$HOME/.local/bin"
            curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh \
              | sh -s -- -b "$HOME/.local/bin"
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> $BASH_ENV
      - run:
          name: "Generate SBOM"
          command: syft . -o cyclonedx-json > sbom.json
      - persist_to_workspace:
          root: .
          paths:
            - sbom.json

  scan_sbom_for_vulnerabilities:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Install Grype"
          command: |
            mkdir -p "$HOME/.local/bin"
            curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh \
              | sh -s -- -b "$HOME/.local/bin"
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> $BASH_ENV
      
      # Run Grype in a "table" or "text" mode so it's easy to read in the job log
      - run:
          name: "Scan SBOM and Print to Console"
          command: grype sbom:./sbom.json -o table

      # Run Grype again to store a JSON report as an artifact for deeper analysis
      - run:
          name: "Generate JSON Report"
          command: grype sbom:./sbom.json -o json > grype-report.json
      
      - store_artifacts:
          path: grype-report.json
          destination: grype-report.json

workflows:
  version: 2
  build-and-scan-workflow:
    jobs:
      - build_and_create_sbom
      - scan_sbom_for_vulnerabilities:
          requires:
            - build_and_create_sbom
