version: 2.1
orbs:
  snyk: snyk/snyk@1.10.0
  sbom-transmitter: manifest-cyber/sbom-transmitter@1.5.0

jobs:
  sbom-generation:
    executor: sbom-transmitter/default
    steps:
      - checkout
      - sbom-transmitter/install-syft
      - sbom-transmitter/run-syft:
          output-format: cyclonedx-json
          output-file: sbom.json
      - persist_to_workspace:
          root: .
          paths: [sbom.json]

  vulnerability-scanning:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      - snyk/scan:
          fail-on-issues: true
          severity-threshold: high
          monitor-on-build: true
          project: ${CIRCLE_PROJECT_REPONAME}
          target-file: sbom.json

  license-compliance:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      - snyk/scan:
          fail-on-issues: true
          scan-type: licences
          license-issues: true
          policy-path: .snyk

workflows:
  security-pipeline:
    jobs:
      - sbom-generation
      - vulnerability-scanning:
          requires: sbom-generation
      - license-compliance:
          requires: sbom-generation
