# .circleci/config.yml
version: 2.1

jobs:
  generate-sbom:
    docker:
      - image: ghcr.io/anchore/syft:alpine  # Alpine variant contains /bin/sh
    resource_class: medium+
    entrypoint: ["/bin/sh", "-c"]  # Explicit shell declaration[8]
    steps:
      - checkout
      - run:
          name: Generate SBOM
          command: |
            syft packages . -o cyclonedx-json=sbom.json
      - persist_to_workspace:
          root: .
          paths: 
            - sbom.json
      - store_artifacts:
          path: sbom.json
          destination: sbom-artifacts

  scan-sbom:
    docker:
      - image: ghcr.io/aquasec/trivy:0.65.0-alpine
    entrypoint: ["/bin/sh", "-c"]
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Vulnerability Scan
          command: |
            trivy sbom --severity CRITICAL,HIGH \
              --exit-code 1 \
              --cache-dir /tmp/trivy-cache \
              /tmp/workspace/sbom.json

workflows:
  security-scan:
    jobs:
      - generate-sbom:
          context: cgroupv2-compat
      - scan-sbom:
          requires: 
            - generate-sbom
          filters:
            branches:
              only: main
