# .circleci/config.yml
version: 2.1

jobs:
  generate_sbom:  # Snake_case naming convention
    docker:
      - image: ghcr.io/anchore/syft:alpine
        entrypoint: ["/bin/sh", "-c"]  # Moved under docker key
    resource_class: medium+
    steps:
      - checkout
      - run:
          name: Generate SBOM
          command: |
            syft packages . -o cyclonedx-json=sbom.json
          shell: /bin/sh  # Moved to run step
      - persist_to_workspace:
          root: .
          paths: 
            - sbom.json
      - store_artifacts:
          path: sbom.json
          destination: sbom-artifacts

  scan_sbom:
    docker:
      - image: ghcr.io/aquasec/trivy:0.65.0-alpine
        entrypoint: ["/bin/sh", "-c"]  # Moved under docker key
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Vulnerability Scan
          command: |
            trivy sbom --severity CRITICAL,HIGH \
              --exit-code 1 \
              --cache-dir /tmp/trivy-cache \
              /tmp/workspace/sbom.json
          shell: /bin/sh  # Moved to run step

workflows:
  security_scan:
    jobs:
      - generate_sbom
      - scan_sbom:
          requires: 
            - generate_sbom
          filters:
            branches:
              only: main
