version: 2.1
orbs:
  snyk: snyk/snyk@2.1.0  # Verified working version from search results
  sbom: manifest/sbom@0.1.0  # Current orb per Manifest Cyber documentation

jobs:
  sbom-generation:
    executor: sbom/default
    steps:
      - checkout
      - sbom/install:
          version: v0.11.0
          generator: syft
          generator_version: v0.92.0
      - sbom/generate:
          generator: syft
          source: .
          output: sbom.json
          format: cyclonedx-json
      - persist_to_workspace:
          root: .
          paths: [sbom.json]

  vulnerability-scanning:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      - snyk/scan:
          fail-on-issues: true
          severity-threshold: high
          target-file: sbom.json
          monitor-on-build: true

  license-compliance:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      - snyk/scan:
          scan-type: licenses
          license-issues: true
          policy-path: .snyk

workflows:
  security-pipeline:
    jobs:
      - sbom-generation
      - vulnerability-scanning:
          requires: 
            - sbom-generation
      - license-compliance:
          requires: 
            - sbom-generation
