version: 2.1

jobs:
  # ----------------------------------------------------------------------
  # 1) Job: build_and_create_sbom
  #    - Checks out the code
  #    - Installs Syft
  #    - Builds/installs dependencies (optional, adjust for your project)
  #    - Generates SBOM with Syft
  #    - Stores SBOM as artifact
  # ----------------------------------------------------------------------
  build_and_create_sbom:
    docker:
      - image: cimg/base:stable  # or another image suitable for your project
    steps:
      - checkout

      # OPTIONAL: Install your project dependencies or do any setup
      # - run: npm install
      # - run: yarn install
      # - run: ./configure && make
      # ... etc.

      - run:
          name: "Install Syft (User Directory)"
          command: |
            mkdir -p "$HOME/.local/bin"
            curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b "$HOME/.local/bin"
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> $BASH_ENV

      - run:
          name: "Generate SBOM"
          command: |
            syft . -o cyclonedx-json > sbom.json

      # Save sbom.json as artifact so it can be used by subsequent jobs
      - store_artifacts:
          path: sbom.json
          destination: sbom.json

  # ----------------------------------------------------------------------
  # 2) Job: scan_sbom_for_vulnerabilities
  #    - Downloads the SBOM artifact from previous job
  #    - Installs Grype
  #    - Runs Grype on the SBOM to detect vulnerabilities
  # ----------------------------------------------------------------------
  scan_sbom_for_vulnerabilities:
    docker:
      - image: cimg/base:stable
    steps:
      # Optionally check out code if needed for scanning; not strictly needed for just scanning the SBOM
      - run:
          name: "Download Artifacts"
          command: |
            mkdir artifacts
            cd artifacts
            circleci-artifacts download --path sbom.json --destination . || echo "No artifacts found"

      - run:
          name: "Install Grype"
          command: |
            curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - run:
          name: "Scan SBOM"
          command: |
            grype sbom:artifacts/sbom.json

workflows:
  version: 2
  build-and-scan-workflow:
    jobs:
      - build_and_create_sbom
      - scan_sbom_for_vulnerabilities:
          requires:
            - build_and_create_sbom
