version: 2.1

jobs:
  sbom-generation:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      - run:
          name: Install Syft
          command: |
            mkdir -p "$HOME/bin"
            echo 'export PATH="$HOME/bin:$PATH"' >> $BASH_ENV
            curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b "$HOME/bin"
            syft version  # Verify installation
      - run:
          name: Generate SBOM
          command: syft packages . -o cyclonedx-json > sbom.json
      - persist_to_workspace:
          root: .
          paths: [sbom.json]

  vulnerability-scanning:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install Grype
          command: |
            mkdir -p "$HOME/bin"
            echo 'export PATH="$HOME/bin:$PATH"' >> $BASH_ENV
            curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b "$HOME/bin"
            grype version  # Verify installation
      - run:
          name: Scan for vulnerabilities
          command: grype sbom:sbom.json --fail-on high

  license-compliance:
    docker:
      - image: cimg/go:1.20
    steps:
      - checkout
      - run:
          name: Install go-licenses
          command: |
            mkdir -p "$HOME/bin"
            echo 'export PATH="$HOME/bin:$PATH"' >> $BASH_ENV
            go install github.com/google/go-licenses@latest
            go-licenses version  # Verify installation
      - run:
          name: Check License Compliance
          command: go-licenses check ./... --disallowed_types=forbidden,restricted

workflows:
  security-pipeline:
    jobs:
      - sbom-generation
      - vulnerability-scanning:
          requires:
            - sbom-generation
      - license-compliance:
          requires:
            - sbom-generation
