version: 2.1

executors:
  ort-executor:
    docker:
      - image: ghcr.io/oss-review-toolkit/ort:latest
    environment:
      ORT_RESULTS_PATH: /project/ort-results
      MAVEN_REPO_LOCAL: /project/cache/.m2/repository
      GO_CACHE_LOCAL: /project/cache/.go/pkg/mod
      PIP_CACHE_DIR: /project/cache/pip
      GRADLE_USER_HOME: /project/cache/.gradle
      YARN_CACHE_FOLDER: /project/cache/yarn
      NODE_PATH: /project/cache/node_modules
      SBT_OPTS: "-Dsbt.global.base=/project/cache/sbt -Dsbt.ivy.home=/project/cache/ivy2 -Divy.home=/project/cache/ivy2"

jobs:
  run-ort:
    executor: ort-executor
    steps:
      # Step 1: Checkout code
      - checkout

      # Step 2: Set up environment variables and directories
      - run:
          name: Initialize Environment Variables and Directories
          command: |
            export ORT_SCAN_STARTED_AT=$(date +"%Y-%m-%dT%H:%M:%S%z")
            mkdir -p /project/{cache,ort-results,scanner/archive/,scanner/provenance/}
            mkdir -p ${MAVEN_REPO_LOCAL} ${GO_CACHE_LOCAL} ${PIP_CACHE_DIR} ${GRADLE_USER_HOME} ${YARN_CACHE_FOLDER} ${NODE_PATH}
            echo "Environment initialized."

      # Step 3: Run ORT Analyzer
      - run:
          name: Run ORT Analyzer
          command: |
            ort analyze \
              -i /project \
              -o ${ORT_RESULTS_PATH} \
              -f JSON \
              --stacktrace

      # Step 4: Run ORT Evaluator (Policy Checks)
      - run:
          name: Run ORT Evaluator
          command: |
            ort evaluate \
              -i ${ORT_RESULTS_PATH}/analyzer-result.json \
              -o ${ORT_RESULTS_PATH} \
              --stacktrace

      # Step 5: Run ORT Reporter (Generate SBOMs and Reports)
      - run:
          name: Generate Reports with ORT Reporter
          command: |
            ort report \
              -i ${ORT_RESULTS_PATH}/evaluation-result.json \
              -o ${ORT_RESULTS_PATH} \
              -f CycloneDx,SpdxDocument,WebApp \
              --stacktrace

      # Step 6: Save Artifacts (Reports)
      - store_artifacts:
          path: /project/ort-results
          destination: ort-reports

workflows:
  version: 2
  ort-workflow:
    jobs:
      - run-ort
