# .circleci/config.yml
version: 2.1

jobs:
  generate-sbom:
    docker:
      - image: aquasec/trivy:0.59
    steps:
      - checkout
      - run:
          name: Generate SBOM
          command: |
            trivy fs --format cyclonedx --output sbom.json .
      - persist_to_workspace:
          root: .
          paths:
            - sbom.json
      - store_artifacts:
          path: sbom.json
          destination: sbom-artifacts

  scan-sbom:
    docker:
      - image: aquasec/trivy:0.59
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Scan SBOM
          command: |
            trivy sbom \
              --severity CRITICAL,HIGH \
              --exit-code 1 \
              --format table \
              /tmp/workspace/sbom.json

workflows:
  sbom-security-scan:
    jobs:
      - generate-sbom
      - scan-sbom:
          requires:
            - generate-sbom
          filters:
            branches:
              only: main
