version: 2.1
jobs:
  build_and_scan:
    docker:
      - image: circleci/python:3.8  # Use an image that fits your project's requirements
    steps:
      - checkout

      # Install Syft and Grype
      - run:
          name: Install Syft and Grype
          command: |
            curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
            curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      # Generate SBOM
      - run:
          name: Generate SBOM with Syft
          command: |
            syft . -o cyclonedx > sbom.json

      # Scan for vulnerabilities using the SBOM
      - run:
          name: Vulnerability Scan with Grype
          command: |
            grype sbom:sbom.json

      # License scanning using ScanCode Toolkit (using a Docker image)
      - run:
          name: Scan for Restricted Licenses
          command: |
            # Adjust the docker image and command as needed. Here we use a hypothetical ScanCode Docker image.
            docker run --rm -v "$(pwd):/src" nfnty/scancode-toolkit scancode -l -c --json-pp scan-results.json /src
            # Optionally, add a script to parse scan-results.json and exit with a non-zero status if restricted licenses are found.

workflows:
  version: 2
  build_and_scan_workflow:
    jobs:
      - build_and_scan
