# .circleci/config.yml
version: 2.1

jobs:
  generate-sbom:
    docker:
      - image: ghcr.io/anchore/syft:latest  # Official Syft image from GitHub Container Registry
    steps:
      - checkout
      - run:
          name: Generate SBOM
          command: |
            syft packages . -o cyclonedx-json=sbom.json
      - persist_to_workspace:
          root: .
          paths:
            - sbom.json
      - store_artifacts:
          path: sbom.json
          destination: sbom-artifacts

  scan-sbom:
    docker:
      - image: ghcr.io/aquasec/trivy:0.65.0  # Verified working version for cgroupv2
    resource_class: medium+
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Vulnerability Scan
          command: |
            trivy sbom --severity CRITICAL,HIGH \
              --exit-code 1 \
              --format sarif \
              --cache-dir /tmp/trivy-cache \
              /tmp/workspace/sbom.json
      - store_artifacts:
          path: /tmp/trivy-cache
          destination: trivy-cache

workflows:
  security-scan:
    jobs:
      - generate-sbom:
          context: cgroupv2-compat
      - scan-sbom:
          requires:
            - generate-sbom
          filters:
            branches:
              only: main
